services:
  postgres_db:
    container_name: teamwork_db
    image: postgres
    environment:
      POSTGRES_USER: teamwork
      POSTGRES_PASSWORD: teamwork
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - postgres_network
volumes:
  postgres_volume:

networks:
  postgres_network:
    driver: bridge
